---
title: "Zip file creation"
format: html
editor: visual
 
---
```{r}
library(zip)
```

## Creation of the zip file for Phase 2

```{r}

#| echo: false
#| message: false



# Set the working directory to the project folder
setwd(here())

# We select the data folder
data_folder <- "data"  

# putting all data files in the folder
data_files <- list.files(data_folder, full.names = TRUE, recursive = TRUE)

# Listing all the files we include in the zip
files_to_zip <- c(
  "Research_project.Rproj",
  data_files,
  "Phase 2 - Data description_files",
  "Phase 2 - Data description.qmd",
  "Phase 2 - Data description.html",
  "README.md"
)

zip_file_name <- "Research_project.zip"

# Creating the zip archive
zip(zip_file_name, files_to_zip)

# To have the confirmation that it works
if (file.exists(zip_file_name)) {
  message("Successfully created ", zip_file_name)
}else{
  message("Failed to create the zip file.")
}



```

## Creation of zip file for phase 3 : final rendering


```{r}
#| echo: false
#| message: false

setwd(here())
# We select the data folder
data_folder_3 <- "data"  

# putting all data files in the folder
data_files_3 <- list.files(data_folder_3, full.names = TRUE, recursive = TRUE)

# Listing all the necessary files
files_to_zip_3 <- c(
  "Research_project.Rproj",
  data_files_3,
  "Phase 2 - Data description.qmd",
  "Phase 3 - Data analysis.qmd",
  "Phase-3---Data-analysis.pdf",
  "README.md"
)

zip_file_name_3 <- "Research_project.zip"

# Creating the zip archive
zipr(zip_file_name_3,files_to_zip_3)

# To have the confirmation that it works
if (file.exists(zip_file_name_3)) {
  message("Successfully created ", zip_file_name_3)
}else{
  message("Failed to create the zip file.")
}

```

